// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/proto/gosched/v1/scheduler.proto

package rpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Duration      int64                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Deadline      int64                  `protobuf:"varint,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	ArrivalTime   int64                  `protobuf:"varint,6,opt,name=arrival_time,json=arrivalTime,proto3" json:"arrival_time,omitempty"`
	Period        int64                  `protobuf:"varint,7,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_api_proto_gosched_v1_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gosched_v1_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_proto_gosched_v1_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Task) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *Task) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Task) GetArrivalTime() int64 {
	if x != nil {
		return x.ArrivalTime
	}
	return 0
}

func (x *Task) GetPeriod() int64 {
	if x != nil {
		return x.Period
	}
	return 0
}

type ScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     string                 `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Workers       int32                  `protobuf:"varint,2,opt,name=workers,proto3" json:"workers,omitempty"`
	Tasks         []*Task                `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleRequest) Reset() {
	*x = ScheduleRequest{}
	mi := &file_api_proto_gosched_v1_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRequest) ProtoMessage() {}

func (x *ScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gosched_v1_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleRequest.ProtoReflect.Descriptor instead.
func (*ScheduleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_gosched_v1_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduleRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *ScheduleRequest) GetWorkers() int32 {
	if x != nil {
		return x.Workers
	}
	return 0
}

func (x *ScheduleRequest) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type ScheduleResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Algorithm         string                 `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	TasksProcessed    int32                  `protobuf:"varint,2,opt,name=tasks_processed,json=tasksProcessed,proto3" json:"tasks_processed,omitempty"`
	Completed         int32                  `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	MissedDeadlines   int32                  `protobuf:"varint,4,opt,name=missed_deadlines,json=missedDeadlines,proto3" json:"missed_deadlines,omitempty"`
	AverageWaitMs     float64                `protobuf:"fixed64,5,opt,name=average_wait_ms,json=averageWaitMs,proto3" json:"average_wait_ms,omitempty"`
	CpuUtilizationPct float64                `protobuf:"fixed64,6,opt,name=cpu_utilization_pct,json=cpuUtilizationPct,proto3" json:"cpu_utilization_pct,omitempty"`
	MaxQueueDepth     int32                  `protobuf:"varint,7,opt,name=max_queue_depth,json=maxQueueDepth,proto3" json:"max_queue_depth,omitempty"`
	TotalSimulatedMs  int64                  `protobuf:"varint,8,opt,name=total_simulated_ms,json=totalSimulatedMs,proto3" json:"total_simulated_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ScheduleResponse) Reset() {
	*x = ScheduleResponse{}
	mi := &file_api_proto_gosched_v1_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResponse) ProtoMessage() {}

func (x *ScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gosched_v1_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResponse.ProtoReflect.Descriptor instead.
func (*ScheduleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_gosched_v1_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *ScheduleResponse) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *ScheduleResponse) GetTasksProcessed() int32 {
	if x != nil {
		return x.TasksProcessed
	}
	return 0
}

func (x *ScheduleResponse) GetCompleted() int32 {
	if x != nil {
		return x.Completed
	}
	return 0
}

func (x *ScheduleResponse) GetMissedDeadlines() int32 {
	if x != nil {
		return x.MissedDeadlines
	}
	return 0
}

func (x *ScheduleResponse) GetAverageWaitMs() float64 {
	if x != nil {
		return x.AverageWaitMs
	}
	return 0
}

func (x *ScheduleResponse) GetCpuUtilizationPct() float64 {
	if x != nil {
		return x.CpuUtilizationPct
	}
	return 0
}

func (x *ScheduleResponse) GetMaxQueueDepth() int32 {
	if x != nil {
		return x.MaxQueueDepth
	}
	return 0
}

func (x *ScheduleResponse) GetTotalSimulatedMs() int64 {
	if x != nil {
		return x.TotalSimulatedMs
	}
	return 0
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_gosched_v1_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gosched_v1_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_gosched_v1_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_proto_gosched_v1_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gosched_v1_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_gosched_v1_scheduler_proto_rawDescGZIP(), []int{4}
}

var File_api_proto_gosched_v1_scheduler_proto protoreflect.FileDescriptor

const file_api_proto_gosched_v1_scheduler_proto_rawDesc = "" +
	"\n" +
	"$api/proto/gosched/v1/scheduler.proto\x12\n" +
	"gosched.v1\"\xb9\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x03R\bduration\x12\x1a\n" +
	"\bdeadline\x18\x04 \x01(\x03R\bdeadline\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12!\n" +
	"\farrival_time\x18\x06 \x01(\x03R\varrivalTime\x12\x16\n" +
	"\x06period\x18\a \x01(\x03R\x06period\"q\n" +
	"\x0fScheduleRequest\x12\x1c\n" +
	"\talgorithm\x18\x01 \x01(\tR\talgorithm\x12\x18\n" +
	"\aworkers\x18\x02 \x01(\x05R\aworkers\x12&\n" +
	"\x05tasks\x18\x03 \x03(\v2\x10.gosched.v1.TaskR\x05tasks\"\xd0\x02\n" +
	"\x10ScheduleResponse\x12\x1c\n" +
	"\talgorithm\x18\x01 \x01(\tR\talgorithm\x12'\n" +
	"\x0ftasks_processed\x18\x02 \x01(\x05R\x0etasksProcessed\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\x05R\tcompleted\x12)\n" +
	"\x10missed_deadlines\x18\x04 \x01(\x05R\x0fmissedDeadlines\x12&\n" +
	"\x0faverage_wait_ms\x18\x05 \x01(\x01R\raverageWaitMs\x12.\n" +
	"\x13cpu_utilization_pct\x18\x06 \x01(\x01R\x11cpuUtilizationPct\x12&\n" +
	"\x0fmax_queue_depth\x18\a \x01(\x05R\rmaxQueueDepth\x12,\n" +
	"\x12total_simulated_ms\x18\b \x01(\x03R\x10totalSimulatedMs\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x0f\n" +
	"\rHealthRequest2\x9a\x01\n" +
	"\x10SchedulerService\x12E\n" +
	"\bSchedule\x12\x1b.gosched.v1.ScheduleRequest\x1a\x1c.gosched.v1.ScheduleResponse\x12?\n" +
	"\x06Health\x12\x19.gosched.v1.HealthRequest\x1a\x1a.gosched.v1.HealthResponseB*Z(github.com/krwg/gosched/pkg/rpc/v1;rpcv1b\x06proto3"

var (
	file_api_proto_gosched_v1_scheduler_proto_rawDescOnce sync.Once
	file_api_proto_gosched_v1_scheduler_proto_rawDescData []byte
)

func file_api_proto_gosched_v1_scheduler_proto_rawDescGZIP() []byte {
	file_api_proto_gosched_v1_scheduler_proto_rawDescOnce.Do(func() {
		file_api_proto_gosched_v1_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_gosched_v1_scheduler_proto_rawDesc), len(file_api_proto_gosched_v1_scheduler_proto_rawDesc)))
	})
	return file_api_proto_gosched_v1_scheduler_proto_rawDescData
}

var file_api_proto_gosched_v1_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_gosched_v1_scheduler_proto_goTypes = []any{
	(*Task)(nil),             // 0: gosched.v1.Task
	(*ScheduleRequest)(nil),  // 1: gosched.v1.ScheduleRequest
	(*ScheduleResponse)(nil), // 2: gosched.v1.ScheduleResponse
	(*HealthResponse)(nil),   // 3: gosched.v1.HealthResponse
	(*HealthRequest)(nil),    // 4: gosched.v1.HealthRequest
}
var file_api_proto_gosched_v1_scheduler_proto_depIdxs = []int32{
	0, // 0: gosched.v1.ScheduleRequest.tasks:type_name -> gosched.v1.Task
	1, // 1: gosched.v1.SchedulerService.Schedule:input_type -> gosched.v1.ScheduleRequest
	4, // 2: gosched.v1.SchedulerService.Health:input_type -> gosched.v1.HealthRequest
	2, // 3: gosched.v1.SchedulerService.Schedule:output_type -> gosched.v1.ScheduleResponse
	3, // 4: gosched.v1.SchedulerService.Health:output_type -> gosched.v1.HealthResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_gosched_v1_scheduler_proto_init() }
func file_api_proto_gosched_v1_scheduler_proto_init() {
	if File_api_proto_gosched_v1_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_gosched_v1_scheduler_proto_rawDesc), len(file_api_proto_gosched_v1_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_gosched_v1_scheduler_proto_goTypes,
		DependencyIndexes: file_api_proto_gosched_v1_scheduler_proto_depIdxs,
		MessageInfos:      file_api_proto_gosched_v1_scheduler_proto_msgTypes,
	}.Build()
	File_api_proto_gosched_v1_scheduler_proto = out.File
	file_api_proto_gosched_v1_scheduler_proto_goTypes = nil
	file_api_proto_gosched_v1_scheduler_proto_depIdxs = nil
}
